services:
  devices-api:
    container_name: devices-api
    build:
      context: devices-api
    ports:
      - "8080:8080"
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
      # according to the doc otlp is default value but after testing this env var seems to be necessary
      OTEL_LOGS_EXPORTER: otlp

  sensor-data-generator:
    container_name: sensor-data-generator
    build:
      context: sensor-data-generator/SensorDataGenerator
      dockerfile: Dockerfile
    ports:
      - "8090:8090"

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    command: [ "--config=/etc/otelcol-config.yml" ]
    volumes:
      - ./otel-collector/otelcol-config.yml:/etc/otelcol-config.yml
