services:
  devices-api:
    container_name: devices-api
    build:
      context: devices-api
    ports:
      - "8080:8080"

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.77.0
    container_name: otel-collector
    command: [ "--config=/etc/otelcol-config.yml" ]
    volumes:
      - ./otel-collector/otelcol-config.yml:/etc/otelcol-config.yml
