kind: Deployment
apiVersion: apps/v1

metadata:
  name: device-api

spec:
  replicas: 1
  selector:
    matchLabels:
      app: device-api
  template:
    metadata:
      labels:
        app: device-api
    spec:
      containers:
        - name: device-api
          image: acr${project-name}.azurecr.io/device-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 150m
              memory: 512Mi
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://otel-contrib-collector:4317"
            - name: OTEL_LOGS_EXPORTER
              value: otlp
            - name: COSMOS_DB_URI
              value: COSMOS_DB_URI_PLACEHOLDER
            - name: COSMOS_DB_KEY
              value: COSMOS_DB_KEY_PLACEHOLDER
            - name: COSMOS_DB_NAME
              value: COSMOS_DB_NAME_PLACEHOLDER

---

apiVersion: v1
kind: Service
metadata:
  name: device-api-service
spec:
  type: LoadBalancer
  ports:
  - port: 8080 
    targetPort: 8080
  selector:
    app: device-api
