kind: Deployment
apiVersion: apps/v1

metadata:
  name: otel-collector

spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: otel-collector
  template:
    metadata:
      labels:
        app.kubernetes.io/name: otel-collector
    spec:
      containers:
        - name: otel-collector
          args:
            - --config=/conf/collector.yaml
          image: otel/opentelemetry-collector-contrib:0.75.0
          volumeMounts:
            - mountPath: /conf
              name: otel-collector-config
          ports:
            - containerPort: 8090
          resources:
            requests:
              cpu: 50m
              memory: 50Mi
            limits:
              cpu: 100m
              memory: 100Mi
      volumes:
        - configMap:
            items:
              - key: collector.yaml
                path: collector.yaml
            name: otel-collector-config
          name: otel-collector-config